// generated by Fast Light User Interface Designer (fluid) version 1.0010

#include "fl_gl_interface.h"

Fl_Slider *rotate=(Fl_Slider *)0;

Fl_Button *exitButton=(Fl_Button *)0;

Fl_DrawP3D_Window *myGlWindow=(Fl_DrawP3D_Window *)0;

Fl_Slider *rotate2=(Fl_Slider *)0;

Fl_Button *redrawButton=(Fl_Button *)0;

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(359, 333);
    w = o;
    o->labeltype(FL_NORMAL_LABEL);
    o->align(FL_ALIGN_TOP_RIGHT);
    { Fl_Slider* o = rotate = new Fl_Slider(20, 295, 200, 15, "rotate");
      o->type(1);
      o->maximum(359);
      o->callback((Fl_Callback*)rot_cb);
      o->align(FL_ALIGN_BOTTOM_LEFT);
    }
    { Fl_Button* o = exitButton = new Fl_Button(245, 295, 60, 20, "exit");
      o->callback((Fl_Callback*)exit_cb);
    }
    { Fl_DrawP3D_Window* o = myGlWindow = new Fl_DrawP3D_Window(25, 25, 285, 235, "label");
      o->box(FL_DOWN_FRAME);
      o->labeltype(FL_NO_LABEL);
    }
    { Fl_Slider* o = rotate2 = new Fl_Slider(330, 25, 15, 205, "rotate2");
      o->maximum(359);
      o->callback((Fl_Callback*)rot_cb);
    }
    { Fl_Button* o = redrawButton = new Fl_Button(245, 270, 60, 20, "redraw");
      o->callback((Fl_Callback*)redraw_cb);
    }
    o->end();
  }
  return w;
}
