// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef fl_gl_interface_h
#define fl_gl_interface_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Slider.H>
extern void rot_cb(Fl_Slider*, void*);
extern Fl_Slider *rotate;
#include <FL/Fl_Button.H>
extern void exit_cb(Fl_Button*, void*);
extern Fl_Button *exitButton;
#include <FL/Fl_Gl_Window.H>
#include "Fl_DrawP3D_Window.h"
extern Fl_DrawP3D_Window *myGlWindow;
extern Fl_Slider *rotate2;
extern void redraw_cb(Fl_Button*, void*);
extern Fl_Button *redrawButton;
Fl_Window* make_window();
#endif
